name: Apollo
main: me.staud.apollo.Apollo
version: 1.0
author: Staud
description: KitPvP Plugin with built in Essentials
softdepend:
  - PermissionsEx

commands:
  kits:
  reset:
  stats:
  report:
  help:
